version: "3"
services:
  minio:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.minio
    container_name: minio-container
    image: zhangtianyi9/voice-collector-minio:1.0.0
    ports:
      - "9000:9000"
    volumes:
      - ./data/voice:/data/local-s3

  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    working_dir: /server
    command: gunicorn -w 4 --bind 0.0.0.0:5000 app:application
    container_name: server-container
    image: zhangtianyi9/voice-collector-server:1.0.0
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.web
      args:
        REACT_APP_SCHEME: "https://"
        REACT_APP_PORT_NUMBER_EXTERNAL: 443
    container_name: web-container
    image: zhangtianyi9/voice-collector-web:1.0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./data/nginx:/var/www/certbot
      - ./dockerfiles/nginx.prod.conf:/etc/nginx/conf.d/default.conf

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./data/nginx:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"