version: '3'
services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: minio-container
    image: minio
    ports:
      - "9000:9000"
    networks:
      - my-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    image: server
    ports:
      - "5000:5000"
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web-container
    image: web
    ports:
      - "3000:80"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
