version: "3"
services:
  minio:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.minio
    container_name: minio-container
    image: minio
    ports:
      - "9000:9000"

  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    working_dir: /server
    command: gunicorn -w 4 --bind 0.0.0.0:5000 app:application
    container_name: server-container
    image: server
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.web
      args:
        REACT_APP_SCHEME: "https://"
        REACT_APP_PORT_NUMBER_EXTERNAL: 443
    container_name: web-container
    image: web
    ports:
      - "3000:80"
