# Build step #1: build the frontend

# Use an official Node runtime as the base image
FROM node:16-alpine as build

# Set environment variables
ENV PATH /web/node_modules/.bin:$PATH

# Set working directory
WORKDIR /web

# Copy package.json and package-lock.json
COPY ./web/package.json ./
COPY ./web/yarn.lock ./
COPY ./web/src ./src
COPY ./web/public ./public

# Set environment variables for React app
ENV REACT_APP_API_URL='http://localhost'
ENV REACT_APP_PORT_NUMBER='3000'

# Install dependencies
RUN yarn install

# Build the app
RUN yarn build

# Build step #2: build the nginx container

# Use an official nginx runtime as the base image
FROM nginx:stable-alpine

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy the frontend build from the build stage
COPY --from=build /web/build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]

